# 01. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

# 02. Importing Data

In [2]:
df = pd.read_pickle(r'C:\Users\Brooke\05-2022 Instacart Basket Analysis\Data\Prepared Data\task 4.10 pt1.pkl')

In [3]:
#check data
df.head()

,user_id,Gender,STATE,Age,date_joined,number_of_dependants,marital_status,income,order_id,order_number,...,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_prices,spending_flag,median_days_since_prior_order,frequency_flag,region,exclude
0,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,No
1,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,No
2,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,No
3,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,No
4,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,No

In [4]:
#check shape
df.shape

(30993489, 34)

In [5]:
#drop exclude column
df.drop(columns = ['exclude'], inplace = True)

In [6]:
#check data
df.head()

,user_id,Gender,STATE,Age,date_joined,number_of_dependants,marital_status,income,order_id,order_number,...,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_prices,spending_flag,median_days_since_prior_order,frequency_flag,region
0,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South
1,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South
2,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South
3,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South
4,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South

In [7]:
#Check shape
df.shape

(30993489, 33)

# 03. Create a Profiling Variable

In [8]:
#see columns
df.columns

Index(['user_id', 'Gender', 'STATE', 'Age', 'date_joined',
       'number_of_dependants', 'marital_status', 'income', 'order_id',
       'order_number', 'orders_day_of_week', 'order_hour_of_day',
       'days_since_prior_order', 'has_prior_orders', 'product_id',
       'add_to_cart_order', 'reordered', '_merge', 'product_name', 'aisle_id',
       'department_id', 'prices', 'price_range_loc', 'busiest_day',
       'busiest_days', 'busiest_period_of_day', 'max_order', 'loyalty_flag',
       'average_prices', 'spending_flag', 'median_days_since_prior_order',
       'frequency_flag', 'region'],
      dtype='object')

In [9]:
#create age profile
df.loc[(df['Age'] >= 18) & (df['Age'] < 30), 'age_group'] = 'Young Adult'

In [10]:
df.loc[(df['Age'] >= 30) & (df['Age'] < 40), 'age_group'] = '30s'

In [11]:
df.loc[(df['Age'] >= 40) & (df['Age'] < 50), 'age_group'] = '40s'

In [12]:
df.loc[(df['Age'] >= 50) & (df['Age'] < 60), 'age_group'] = '50s'

In [13]:
df.loc[(df['Age'] >= 60) & (df['Age'] < 70), 'age_group'] = '60s'

In [14]:
df.loc[(df['Age'] >= 70) & (df['Age'] < 80), 'age_group'] = '70s'

In [15]:
df.loc[df['Age'] >= 80, 'age_group'] = '80s and beyond'

In [17]:
#check data
df.head(60)

,user_id,Gender,STATE,Age,date_joined,number_of_dependants,marital_status,income,order_id,order_number,...,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_prices,spending_flag,median_days_since_prior_order,frequency_flag,region,age_group
0,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
1,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
2,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
3,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
4,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
5,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
6,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
7,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
8,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
9,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
10,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
11,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
12,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
13,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
14,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
15,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
16,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
17,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
18,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
19,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
20,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
21,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
22,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
23,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
24,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
25,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
26,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
27,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
28,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Least busy days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
29,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
30,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
31,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
32,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Regularly busy,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
33,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
34,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
35,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
36,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
37,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
38,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
39,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
40,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
41,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
42,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
43,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
44,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
45,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
46,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
47,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
48,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
49,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Busiest days,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
50,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
51,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
52,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
53,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
54,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
55,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
56,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
57,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
58,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Least busy days,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s
59,2,Female,Alaska,68,7/4/2017,3,married,64940,2168274,1,...,Regularly busy,Most Orders,14,Regular customer,7.515897,Low spender,13.0,Regular customer,West,60s

In [18]:
#create income profile
df.loc[(df['income'] >= 0) & (df['income'] < 50000), 'income_class'] = 'Low income'

In [19]:
df.loc[(df['income'] >= 50000) & (df['income'] < 100000), 'income_class'] = 'Middle income'

In [20]:
df.loc[(df['income'] >= 100000) & (df['income'] < 150000), 'income_class'] = 'Upper-middle income'

In [21]:
df.loc[df['income'] >= 150000, 'income_class'] = 'Upper income'

In [22]:
#check data
df.head(60)

,user_id,Gender,STATE,Age,date_joined,number_of_dependants,marital_status,income,order_id,order_number,...,busiest_period_of_day,max_order,loyalty_flag,average_prices,spending_flag,median_days_since_prior_order,frequency_flag,region,age_group,income_class
0,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
1,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
2,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
3,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
4,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
5,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
6,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
7,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
8,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
9,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
10,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
11,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
12,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
13,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
14,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
15,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
16,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
17,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
18,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
19,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
20,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
21,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
22,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
23,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
24,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
25,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
26,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
27,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
28,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
29,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
30,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
31,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
32,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
33,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
34,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
35,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
36,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
37,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
38,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
39,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
40,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
41,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
42,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
43,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
44,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
45,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
46,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
47,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
48,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
49,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,Most Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
50,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
51,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
52,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
53,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
54,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
55,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
56,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
57,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
58,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,Average Orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income
59,2,Female,Alaska,68,7/4/2017,3,married,64940,2168274,1,...,Most Orders,14,Regular customer,7.515897,Low spender,13.0,Regular customer,West,60s,Middle income

In [23]:
#create department profile
df.loc[df['department_id'] == 1, 'department'] = 'Frozen'

In [24]:
df.loc[df['department_id'] == 2, 'department'] = 'Other'

In [25]:
df.loc[df['department_id'] == 3, 'department'] = 'Bakery'

In [26]:
df.loc[df['department_id'] == 4, 'department'] = 'Produce'

In [27]:
df.loc[df['department_id'] == 5, 'department'] = 'Alcohol'

In [28]:
df.loc[df['department_id'] == 6, 'department'] = 'International'

In [29]:
df.loc[df['department_id'] == 7, 'department'] = 'Beverages'

In [30]:
df.loc[df['department_id'] == 8, 'department'] = 'Pets'

In [31]:
df.loc[df['department_id'] == 9, 'department'] = 'Dry Goods Pasta'

In [32]:
df.loc[df['department_id'] == 10, 'department'] = 'Bulk'

In [33]:
df.loc[df['department_id'] == 11, 'department'] = 'Personal Care'

In [34]:
df.loc[df['department_id'] == 12, 'department'] = 'Meat Seafood'

In [35]:
df.loc[df['department_id'] == 13, 'department'] = 'Pantry'

In [36]:
df.loc[df['department_id'] == 14, 'department'] = 'Breakfast'

In [37]:
df.loc[df['department_id'] == 15, 'department'] = 'Canned Goods'

In [38]:
df.loc[df['department_id'] == 16, 'department'] = 'Dairy Eggs'

In [39]:
df.loc[df['department_id'] == 17, 'department'] = 'Household'

In [40]:
df.loc[df['department_id'] == 18, 'department'] = 'Babies'

In [41]:
df.loc[df['department_id'] == 19, 'department'] = 'Snacks'

In [42]:
df.loc[df['department_id'] == 20, 'department'] = 'Deli'

In [43]:
df.loc[df['department_id'] == 21, 'department'] = 'Missing'

In [44]:
#Check data
df.head(60)

,user_id,Gender,STATE,Age,date_joined,number_of_dependants,marital_status,income,order_id,order_number,...,max_order,loyalty_flag,average_prices,spending_flag,median_days_since_prior_order,frequency_flag,region,age_group,income_class,department
0,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
1,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
2,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
3,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
4,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Household
5,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
6,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
7,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
8,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce
9,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
10,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Breakfast
11,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
12,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
13,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
14,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
15,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Pantry
16,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
17,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
18,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
19,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
20,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Household
21,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
22,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
23,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
24,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
25,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce
26,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce
27,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce
28,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce
29,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
30,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
31,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
32,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
33,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
34,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
35,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
36,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
37,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Breakfast
38,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
39,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
40,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
41,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
42,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
43,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
44,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
45,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
46,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
47,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
48,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
49,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
50,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
51,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages
52,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
53,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
54,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
55,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
56,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs
57,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Breakfast
58,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,10,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks
59,2,Female,Alaska,68,7/4/2017,3,married,64940,2168274,1,...,14,Regular customer,7.515897,Low spender,13.0,Regular customer,West,60s,Middle income,Snacks

In [47]:
#create dependants profile
df.loc[df['number_of_dependants'] == 0, 'parental_status'] = 'No Kids at Home'

In [48]:
df.loc[df['number_of_dependants'] > 0, 'parental_status'] = 'Kids at Home'

In [49]:
#check data
df.head(60)

,user_id,Gender,STATE,Age,date_joined,number_of_dependants,marital_status,income,order_id,order_number,...,loyalty_flag,average_prices,spending_flag,median_days_since_prior_order,frequency_flag,region,age_group,income_class,department,parental_status
0,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
1,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
2,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
3,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
4,1,Female,Alabama,31,2/17/2019,3,married,40423,2539329,1,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Household,Kids at Home
5,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
6,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
7,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
8,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce,Kids at Home
9,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
10,1,Female,Alabama,31,2/17/2019,3,married,40423,2398795,2,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Breakfast,Kids at Home
11,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
12,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
13,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
14,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
15,1,Female,Alabama,31,2/17/2019,3,married,40423,473747,3,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Pantry,Kids at Home
16,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
17,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
18,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
19,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
20,1,Female,Alabama,31,2/17/2019,3,married,40423,2254736,4,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Household,Kids at Home
21,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
22,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
23,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
24,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
25,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce,Kids at Home
26,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce,Kids at Home
27,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce,Kids at Home
28,1,Female,Alabama,31,2/17/2019,3,married,40423,431534,5,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Produce,Kids at Home
29,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
30,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
31,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
32,1,Female,Alabama,31,2/17/2019,3,married,40423,3367565,6,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
33,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
34,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
35,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
36,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
37,1,Female,Alabama,31,2/17/2019,3,married,40423,550135,7,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Breakfast,Kids at Home
38,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
39,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
40,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
41,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
42,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
43,1,Female,Alabama,31,2/17/2019,3,married,40423,3108588,8,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
44,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
45,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
46,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
47,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
48,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
49,1,Female,Alabama,31,2/17/2019,3,married,40423,2295261,9,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
50,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
51,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Beverages,Kids at Home
52,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
53,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
54,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
55,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
56,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Dairy Eggs,Kids at Home
57,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Breakfast,Kids at Home
58,1,Female,Alabama,31,2/17/2019,3,married,40423,2550362,10,...,New customer,6.367797,Low spender,20.5,Non-frequent customer,South,30s,Low income,Snacks,Kids at Home
59,2,Female,Alaska,68,7/4/2017,3,married,64940,2168274,1,...,Regular customer,7.515897,Low spender,13.0,Regular customer,West,60s,Middle income,Snacks,Kids at Home

In [ ]:
df.to_pickle(r'C:\Users\Brooke\05-2022 Instacart Basket Analysis\Data\Prepared Data\task 4.10 continued.pkl')